Encrypt, Signing and Certs
confidentialcontainer/document pull request #1
Opened 2021-12-11 03:20 UTC by huoqifeng

Signed-off-by: huoqifeng <huoqif@cn.ibm.com>

2021-12-11 04:16 UTC, liudalibj requested changes
一些typo的小问题，还有就是, 和 ，的问题，中文尽量统一用，号吧

2021-12-11 04:16 UTC, liudalibj commented on 安全基本概念/加密签名与证书.md
> +当然，在生成私钥和公钥的时候还有很对其他的参数，这里只是给一个简单的例子。
很对其他的参数 --> 很多其他的参数

2021-12-11 04:16 UTC, liudalibj commented on 安全基本概念/加密签名与证书.md
> +只是一个示例。更多的参数可以参考`openssl`的帮助，需要注意的是CSR和CA都是跟域名想关联的。
都是跟域名想关联的。--> 都是跟域名相关联的。

2021-12-11 04:16 UTC, liudalibj commented on 安全基本概念/加密签名与证书.md
> +CSR生成以后，就可以发送给CA了，这里面没有太对好说得，一般都是网站上传，基于https，https是http over ssl|tls。ssl和tls是tcl层实现传输层安全的协议。基本上tls可以看作ssl的升级，因为一些安全性问题，ssl已经不再使用了，推荐的是tls1.2或更高，但是为了表达的方便，我们有时候还是会说基于ssl。
这里面没有太对好说得 --> 这里面没有太多好说得

2021-12-11 04:16 UTC, liudalibj commented on 安全基本概念/加密签名与证书.md
> +CA收到CSR之后会验证信息的有效性，顺便提一下，这个验证工作和后面的责任是CA费用昂贵的部分原因。然后用CA的私钥给这个Website owner的公钥签名。注意，
注意，--> 注意：
这里用冒号是不是好些？

2021-12-11 04:16 UTC, liudalibj commented on 安全基本概念/加密签名与证书.md
> +我们有时候也看到`pfs`后缀的文件（(predecessor of PKCS#12)），这个是问什么呢？
这个是问什么呢？ --> 这个是为什么呢？

2021-12-11 04:16 UTC, liudalibj commented on 安全基本概念/加密签名与证书.md
> +最后，用户在反问网站的时候，浏览器做的第一件事就是下载和验证这个CRT，这是因为CRT是CA签过的，而主流的浏览器都内置了主流CA的公钥。
用户在反问网站的时候 --> 用户在访问网站的时候

2021-12-11 04:16 UTC, liudalibj commented on 安全基本概念/加密签名与证书.md
> +对称加密经常用在 Data at rest, Data in use/memory, 比如磁盘加密，内存加密。
, --> ，

2021-12-11 04:16 UTC, liudalibj commented on 安全基本概念/加密签名与证书.md
> +社交上的信任跟我们日常生活中的信任是一样的，比如，Google， IBM， Microsoft口碑比较好，我们信任他们，签名解决的就是社交上的信任。
， --> ，

2021-12-11 04:16 UTC, liudalibj commented on 安全基本概念/加密签名与证书.md
> +我们这里说的密钥指的是非对称加密的密钥对，分为公钥和私钥，上面解释过了，在生成密钥以及后续步骤的一系列文件的时候我们都会用到一个著名的工具`openssl`, 用`openssl`生成密钥的命令：
, --> ，

2021-12-11 04:16 UTC, liudalibj commented on 安全基本概念/加密签名与证书.md
> +这个生成的证书一般是一个 `.crt` 文件， 这个文件符合x.509规范，什么是 `x.509`?
， --> ，

2021-12-18 02:03 UTC, huoqifeng commented on 安全基本概念/加密签名与证书.md
> +当然，在生成私钥和公钥的时候还有很对其他的参数，这里只是给一个简单的例子。
Done

2021-12-18 02:04 UTC, huoqifeng commented on 安全基本概念/加密签名与证书.md
> +CSR生成以后，就可以发送给CA了，这里面没有太对好说得，一般都是网站上传，基于https，https是http over ssl|tls。ssl和tls是tcl层实现传输层安全的协议。基本上tls可以看作ssl的升级，因为一些安全性问题，ssl已经不再使用了，推荐的是tls1.2或更高，但是为了表达的方便，我们有时候还是会说基于ssl。
Done

2021-12-18 02:04 UTC, huoqifeng commented on 安全基本概念/加密签名与证书.md
> +我们有时候也看到`pfs`后缀的文件（(predecessor of PKCS#12)），这个是问什么呢？
Done

2021-12-18 02:04 UTC, huoqifeng commented on 安全基本概念/加密签名与证书.md
> +对称加密经常用在 Data at rest, Data in use/memory, 比如磁盘加密，内存加密。
Done

2021-12-18 02:04 UTC, huoqifeng commented on 安全基本概念/加密签名与证书.md
> +最后，用户在反问网站的时候，浏览器做的第一件事就是下载和验证这个CRT，这是因为CRT是CA签过的，而主流的浏览器都内置了主流CA的公钥。
Done

2021-12-18 02:04 UTC, huoqifeng commented on 安全基本概念/加密签名与证书.md
> +我们这里说的密钥指的是非对称加密的密钥对，分为公钥和私钥，上面解释过了，在生成密钥以及后续步骤的一系列文件的时候我们都会用到一个著名的工具`openssl`, 用`openssl`生成密钥的命令：
Done

2021-12-18 02:04 UTC, huoqifeng commented on 安全基本概念/加密签名与证书.md
> +这个生成的证书一般是一个 `.crt` 文件， 这个文件符合x.509规范，什么是 `x.509`?
Done

2021-12-18 02:04 UTC, huoqifeng commented on 安全基本概念/加密签名与证书.md
> +社交上的信任跟我们日常生活中的信任是一样的，比如，Google， IBM， Microsoft口碑比较好，我们信任他们，签名解决的就是社交上的信任。
Done

2021-12-18 02:05 UTC, huoqifeng commented on 安全基本概念/加密签名与证书.md
> +只是一个示例。更多的参数可以参考`openssl`的帮助，需要注意的是CSR和CA都是跟域名想关联的。
Done

2021-12-18 02:06 UTC, huoqifeng commented on 安全基本概念/加密签名与证书.md
> +CA收到CSR之后会验证信息的有效性，顺便提一下，这个验证工作和后面的责任是CA费用昂贵的部分原因。然后用CA的私钥给这个Website owner的公钥签名。注意，
Done

2021-12-20 01:46 UTC, liudalibj approved these changes
LGTM

2021-12-20 01:47 UTC, merged